language: csharp
mono: none
dotnet: 2.0.0

notifications:
  email: false

script:
  - cd src
  - dotnet restore
  - dotnet build 
  - dotnet test SecretSanta.Authentication.Tests/
  - dotnet test SecretSanta.Web.Tests/
  - dotnet test SecretSanta.Data.Tests/